services:
  test:
    build: .
    command: pytest src/tests/ -v --tb=short
    environment:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
